# Generated by Django 5.2.4 on 2025-07-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomcategories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomcategory',
            options={'verbose_name': 'Room Category', 'verbose_name_plural': 'Room Categories'},
        ),
    ]
