# Generated by Django 5.2.4 on 2025-07-15 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('statuscatalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreservation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statuscatalogs.statuscatalog'),
        ),
    ]
